[chore] follow codeql recommendation
open-telemetry/opentelemetry-collector pull request #10165
Opened 2024-05-15 22:46 UTC by codeboten

CodeQL is currently reporting "Invalid Go toolchain version: As of Go 1.21, toolchain versions must use the 1.N.P syntax.". This PR attempts to fix this.

2024-05-16 13:41 UTC, mx-psi requested changes
This breaks our compatibility promise: we are dropping support for Go 1.21.x for x less than 10. There were also recently some fixes upstream (see golang/go@27ed85d4d1702e868730ab6ea2ad6326988c615c) that I think should make this message go away.

2024-05-16 14:01 UTC, codeboten commented
> This breaks our compatibility promise: we are dropping support for Go 1.21.x for x less than 10. There were also recently some fixes upstream (see [golang/go@27ed85d](https://github.com/golang/go/commit/27ed85d4d1702e868730ab6ea2ad6326988c615c)) that I think should make this message go away.

Happy to close this, however this PR does bring up a good question of whether we should support versions of go 1.21.x with known CVEs.

2024-05-16 16:35 UTC, mx-psi commented
> > This breaks our compatibility promise: we are dropping support for Go 1.21.x for x less than 10. There were also recently some fixes upstream (see [golang/go@27ed85d](https://github.com/golang/go/commit/27ed85d4d1702e868730ab6ea2ad6326988c615c)) that I think should make this message go away.
> 
> Happy to close this, however this PR does bring up a good question of whether we should support versions of go 1.21.x with known CVEs.

We should definitely encourage using the latest version. We could add a `toolchain` directive on the builder to force the latest version to be used.

In terms of support however, I don't think we lose much by continuing to support those versions, but we can discuss it!

2024-05-16 16:51 UTC, codeboten commented
> In terms of support however, I don't think we lose much by continuing to support those versions, but we can discuss it!

Right, I'm thinking that if we were to only support versions greater than any with known CVEs it would act as incentive to any consumers of the collector libraries to also update to newer versions. I can open a separate issue to discuss and close this PR after I do so.

2024-05-20 09:39 UTC, bogdandrutu commented
100% we should enforce latest (hopefully no CVEs) version when we build the final binary that we release as a binary, but for libraries like artifacts we cannot enforce this.

2024-05-21 18:25 UTC, codeboten commented
@mx-psi @bogdandrutu to appease codeql and ensure we continue to support all version 1.21, i updated the version in go.mod to 1.21.0

2024-05-22 10:23 UTC, mx-psi approved these changes
LGTM. I'd like us to revisit `1.21` vs `1.21.0` once the patch I mentioned above in golang/go is released, but I am okay with doing this for now

2024-05-23 16:38 UTC, merged