zipkin receiver: restore previous behavior
open-telemetry/opentelemetry-collector pull request #1893
Opened 2020-10-02 18:04 UTC by chris-smith-zocdoc

**Description:**
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/1888

Restores the previous behavior where the zipkin receiver parses string tags to other datatypes (int/bool/float)

If this should be a configuration option, please let me know and I'll change it @kbrockhoff @tigrannajaryan 

**Link to tracking Issue:** #1888 

**Testing:** 
Added test

2020-10-02 18:07 UTC, chris-smith-zocdoc commented on translator/trace/zipkin/zipkinv2_to_traces.go
> +		switch tracetranslator.DetermineValueType(val, false) {
Should be noted that the v1 conversion code is currently parsing strings https://github.com/open-telemetry/opentelemetry-collector/blob/master/translator/trace/zipkin/zipkinv1_to_protospan.go#L256 and that these should be consistent

2020-10-06 13:33 UTC, tigrannajaryan requested changes
Blocking until discussion https://github.com/open-telemetry/opentelemetry-collector/issues/1888 is resolved.

2020-10-21 13:50 UTC, tigrannajaryan commented
I am removing the Stale label since @chris-smith-zocdoc is going to submit an update the PR as agreed in https://github.com/open-telemetry/opentelemetry-collector/issues/1888#issuecomment-712900038

2020-10-28 03:45 UTC, chris-smith-zocdoc commented
@tigrannajaryan I've pushed commits to address your feedback. The string parsing behavior is now opt-in using a new option in the zipkin receiver. If this approach looks good to you I can work on fixing the codecoverage

2020-10-28 14:18 UTC, tigrannajaryan commented on receiver/zipkinreceiver/config.go
> +	ParseStringTags bool `mapstructure:"parse_string_tags"`
Add comment to explain the option.

2020-10-28 14:18 UTC, tigrannajaryan commented on receiver/zipkinreceiver/trace_receiver_test.go
> +func TestReceiverConvertsStringsToTypes(t *testing.T) {
Nice test.

2020-10-28 14:18 UTC, tigrannajaryan commented on translator/trace/zipkin/zipkinv1_to_protospan.go
> +	if parseStringTags {
@owais this changes Zipkinv1 receiver behavior. Any concerns with this breaking something that we care about?

2020-10-29 16:51 UTC, tigrannajaryan commented
@chris-smith-zocdoc the approach looks good to me.

2020-10-30 18:04 UTC, tigrannajaryan approved these changes
LGTM. Thanks for your patience.

2020-10-30 18:04 UTC, merged