Introduce a custom retrying mechanism for the PRW exporter
open-telemetry/opentelemetry-collector pull request #3214
Opened 2021-05-18 04:04 UTC by rakyll

With the existing retry mechanism, we can see "out of the order" samples because a failed remote write with older samples can be retried after a successful remote write with relatively new samples. This change is removing the collector's retrying mechanism and replacing it with a custom retryer. min_backoff and max_backoff are similar to the settings available in the Prometheus server.

Fixes #3209.

2021-05-18 12:34 UTC, carlosalberto approved these changes

2021-05-18 22:08 UTC, rakyll commented
Rebased.

2021-05-19 13:46 UTC, dashpole approved these changes

2021-05-19 14:24 UTC, tigrannajaryan commented on exporter/prometheusremotewriteexporter/README.md
> +  - `max_backoff` maximum time to wait before retrying, e.g. "100ms".
For uniformness can we use setting names which match the `RetrySettings`, e.g. initial_interval, max_interval and max_elapsed_time?

2021-05-19 14:24 UTC, tigrannajaryan commented on exporter/prometheusremotewriteexporter/exporter.go
> +		time.Sleep(backoff)
I think random jitter would be also desirable. Consider using "github.com/cenkalti/backoff/v4" which provides a nice exponential backoff algo out of the box (we already use it in queued_retry helper).

2021-05-19 19:29 UTC, bogdandrutu requested changes
This logic seems to be equivalent with Retry logic in the exporter helper, why do we need duplicate code?

I am not sure (not explained in the description at least) why does this work and the exporterhelper logic doesn't?

2021-05-19 19:29 UTC, bogdandrutu commented on exporter/prometheusremotewriteexporter/exporter.go
> +	namespace := prwe.cfg.Namespace
Good change but unrelated.

2021-05-19 22:00 UTC, rakyll commented
@bogdandrutu Isn't exporterhelper retry will try to retry the PushMetrics if anything fails transiently? A successful PushMetrics with newer timestamps can be done before a PushMetrics retry with older samples. The description is explaining the case.

2021-05-19 22:17 UTC, bogdandrutu commented
@rakyll in parallel with me trying to understand better the difference (still not get it from description), I want if possible to separate cosmetic changes so this PR gets more focused :)

2021-05-19 22:28 UTC, Aneurysm9 approved these changes

2021-05-19 22:35 UTC, bogdandrutu commented
Ok I think I understand now. I see that you wait for an entire pdata.Metrics to be pushed (actually that is what the retry do as well, but you split the request after queue-retry helper so if you do that before would be exactly what you do here), but this still does not guarantee out of order problem.

Let's say you have prometheus receiver that scrapes metrics every 10 sec for a target, so you receive and "execute" an initial request for a timeseries "A" that gets retried with backoff for 20sec, then you get a new request from the receiver in 10 seconds that includes the timeseries "A" and push this one, the backoff request will be out of order.

You don't have any guarantee of ordering between consecutive requests to the exporter. Do I miss anything?

2021-05-19 22:35 UTC, rakyll commented
@bogdandrutu I'll remove the cosmetic/organizational changes. 

As far as I can understand, with the exporterhelper, you can have the execution order like the following:

```
PushMetrics1 (failed)
PushMetrics2 (success)
PushMetrics1 (retried) 
```

PushMetrics1 may fail with "out of order samples" because it may contain samples older than PushMetrics2.

2021-05-19 22:36 UTC, bogdandrutu commented
@rakyll Indeed, but what does protect this to happen now?

2021-05-19 22:42 UTC, rakyll commented
@bogdandrutu Ah, I thought that PushMetrics is guarded by a mutex after seeing this:

```
prwe.wg.Add(1)
defer prwe.wg.Done()
```

Turns out it's for the graceful shutdown. I think we need a single flight pattern or buffer the incoming stuff by timeseries and consume from there. I'll work on this PR.

2021-05-19 22:49 UTC, bogdandrutu commented
You can enable the queue from helper with one worker hardcoded config to get that for free.

2021-05-19 23:49 UTC, rakyll commented
@bogdandrutu, we have a hardcoded queue with NumConsumers=1. Does this guarantee that PushMetrics will always be called in the chronological order? I cant find a lot of docs explaining how retries are handled in the pipeline.

2021-05-20 17:26 UTC, bogdandrutu approved these changes
@rakyll yes that works:
1. please add a comment to that to explain why is needed.
2. please add a comment in the new custom retry to explain why this works vs the exporterhelper

2021-05-21 01:35 UTC, rakyll commented
If NumConsumers=1 is guaranteed the retry order, this change is not needed. I'm closing this PR.

2021-05-21 01:35 UTC, closed without merging