Handle graceful shutdown in main
open-telemetry/opentelemetry-collector pull request #3577
Opened 2021-07-08 05:43 UTC by rakyll

service.Collector is handling the signal management and implementing a graceful shutdown. This is a problem for collectors that want to wire their own signal handling in cases they want to add custom logic and/or have resources other than the service.Collector to shutdown. Moving the graceful shutdown out of the service package to let the main programs do the wiring themselves.

Fixes #3490

2021-07-08 05:43 UTC, rakyll commented
One cool fact about this PR is that it's partly written by GitHub Copilot.

2021-07-08 14:46 UTC, tigrannajaryan requested changes
This removes a functionality that was previously available to other distros. Other distros that needs this will have to reimplement it.

Instead of removing it can we make it optional or decouple it in some other way from service.Collector so that distros that don't need it are not forced to use it and distros that do need it can still continue using it?

2021-07-08 17:17 UTC, rakyll commented
Can we file some issues on the distros and make sure they are switching to the new model?

2021-07-08 23:47 UTC, tigrannajaryan commented
> Can we file some issues on the distros and make sure they are switching to the new model?

We can, but what's the new model? Do we suggest that they copy runInteractive, runService and shutdownGracefully functions? It would be nicer if we offered the functionality in some more easily usable way to other distros (and to our own contrib, which is another distro in this context :-) ).

2021-07-09 00:34 UTC, rakyll commented
@tigrannajaryan A distro already needs to write the main program from scratch including the windows bits. Nonetheless, I'll introduce an option to the collector settings, so this is not a breaking change.

2021-07-09 23:25 UTC, rakyll commented
PTAL

2021-07-12 22:08 UTC, carlosalberto approved these changes

2021-07-13 18:34 UTC, tigrannajaryan approved these changes

2021-07-13 18:35 UTC, merged