Rename `logging` exporter to `debug` exporter
open-telemetry/opentelemetry-collector pull request #3609
Opened 2021-07-13 16:53 UTC by sincejune

**Description:**
This PR renamed `logging` exporter to `debug` exporter.

**Link to tracking Issue:**
Closes #3524 

**Testing:**
Verified locally.

**Documentation:**
Also modified all the `logging` exporter usage in the documentations and example configs.

2021-07-13 17:52 UTC, tigrannajaryan requested changes
This is a breaking change and I do not see a good justification for it. https://github.com/open-telemetry/opentelemetry-collector/issues/3524 does not have a good enough justification.

2021-07-29 16:18 UTC, alolita approved these changes

2021-07-29 18:23 UTC, carlosalberto approved these changes

2021-07-29 18:28 UTC, dashpole approved these changes

2021-08-14 03:16 UTC, closed without merging