add support for exporting internal metrics via OpenTelemetry library.
open-telemetry/opentelemetry-collector pull request #3816
Opened 2021-08-10 19:21 UTC by kirbyquerby

**Description:** add support for exporting internal metrics via OpenTelemetry library.

This change adds a new flag `--metrics-backend` which can be set to `opentelemetry` to use the [OpenTelemetry Prometheus exporter](https://github.com/open-telemetry/opentelemetry-go/tree/main/exporters/prometheus) for internal metrics instead of the current OpenCensus implementation. The flag defaults to `opencensus`, preserving the current functionality. There will be follow up PRs that actually set up the existing internal metrics to be exported via the OpenTelemetry library (currently, the exporter will start but will not expose any metrics).

**Link to tracking Issue:** Updates #816 

**Testing:** Added unit tests for the new flag and manually tested to make sure the current internal metrics are still exported correctly using OpenCensus when `--metrics-backend` isn't set.

/cc @odeke-em

2021-08-11 11:02 UTC, tigrannajaryan reviewed
@kirbyquerby Thanks for starting this effort.

2021-08-11 22:00 UTC, odeke-em commented on config/configtelemetry/configtelemetry.go
> +	flags.Var(metricsBackendPtr,
@tigrannajaryan please note that the use of the flag is temporary to ensure that there is parity between exports from either OpenTelemetry or OpenCensus, but essentially the purpose of this PR is to enable the eventual replacement and removal of the OpenCensus dependencies.

2021-08-12 01:31 UTC, kirbyquerby commented on service/telemetry.go
> +		otelHandler, err := tel.initOpenTelemetry()
Yeah

2021-08-12 08:35 UTC, tigrannajaryan commented on config/configtelemetry/configtelemetry.go
> +	flags.Var(metricsBackendPtr,
@odeke-em yes, I understand. It is fine for now. I was just suggesting that we should probably use the opportunity and get rid of the `--metric-level` flag and move telemetry-related settings to the config file.

2021-08-16 20:45 UTC, alolita commented
@Aneurysm9 @rakyll can you please review?

2021-08-16 21:59 UTC, bogdandrutu commented on config/configtelemetry/configtelemetry.go
> +	flags.Var(metricsBackendPtr,
We already started to remove the command line flags, I think we should start this effort for telemetry as well.

2021-08-17 02:37 UTC, kirbyquerby commented on config/configtelemetry/configtelemetry.go
> +	flags.Var(metricsBackendPtr,
Created #3843 to track moving from command-line flags to config + added a TODO

2021-08-17 15:09 UTC, Aneurysm9 approved these changes

2021-08-18 03:50 UTC, kirbyquerby commented
@bogdandrutu would you mind taking a look at this PR?

2021-08-18 16:23 UTC, dashpole reviewed
Does this mean we will have to maintain OC and OTel instrumentation side-by-side for a long time?  It seems likely that OC and OTel instrumentation will diverge subtly over time without extensive testing...

As an alternative, I would propose that we use _both_ opencensus and opentelemetry client libraries at the same time while we migrate.  We can use the [OpenCensus bridge for OpenTelemetry](https://github.com/open-telemetry/opentelemetry-go/tree/main/bridge/opencensus#metrics) to make both opencensus and opentelemetry clients serve metrics on the same prometheus endpoint.

We could roll this out with the following steps:

1. Switch from the OpenCensus prometheus exporter to a "wrapped" OpenTelemetry prometheus exporter.  Verify that self-obs metrics on the prometheus endpoint remain the same.
2. Add the OpenTelemetry API/SDK and use the same prometheus exporter that OC uses.
3. Migrate each metric from OC to OTel individually, and verify that the metric doesn't change.

2021-08-19 23:09 UTC, kirbyquerby commented
@dashpole thanks for the suggestion! I tried the bridge, but ran into two problems:
* It looks like the otel Prometheus `Exporter` [does not implement metric.Exporter](https://pkg.go.dev/go.opentelemetry.io/otel/exporters/prometheus@v0.22.0?utm_source=gopls#Exporter), so I'm not able to pass it into `opencensus.NewMetricExporter()`
* The `metricexport.Exporter` returned by [`opencensus.NewMetricExporter`](https://pkg.go.dev/go.opentelemetry.io/otel/bridge/opencensus@v0.21.0?utm_source=gopls#NewMetricExporter) can't be passed into [`view.RegisterExporter`](https://pkg.go.dev/go.opencensus.io/stats/view?utm_source=gopls#RegisterExporter) which expects a [`view.Exporter`](https://pkg.go.dev/go.opencensus.io/stats/view?utm_source=gopls#Exporter) instead.

Any idea where I'm going wrong?

2021-08-24 18:39 UTC, alolita commented
@dashpole thoughts? It looks like your suggestion doesn't fit the use case being tested.

2021-08-31 01:02 UTC, bogdandrutu requested changes
We are starting with a "public" change that we don't want to support in the future (flags), and the flag is a no-op. Why do we need this then?

2021-08-31 02:28 UTC, kirbyquerby commented
@bogdandrutu The intent of the flag is to allow us to iteratively migrate without breaking existing functionality and then delete the OpenCensus code once we're sure everything works. The alternative would be to switch everything out all at once -- would that be preferable?

2021-09-03 09:06 UTC, bogdandrutu commented
Not sure how is the plan going to work, please describe. I am not suggesting to do a big change, but to do incremental changes that will not be hocked until the last PR when we are ready with everything, then we can have that change flag protected

2021-09-07 19:31 UTC, kirbyquerby commented
@bogdandrutu the current plan is to make incremental changes guarded behind a flag that defaults to OpenCensus, change the default to OpenTelemetry once we're fairly confident we have feature parity, and then finally remove the flag (along with the OpenCensus code) once we're confident the migration is stable.

Are you suggesting we still make incremental changes but make the new code completely unreachable, and only add the flag once all of the code has been added?

2021-09-13 20:49 UTC, kirbyquerby commented
@bogdandrutu I've removed the flag and made a const bool to control the behavior instead. PTAL.

2021-09-22 18:17 UTC, Aneurysm9 commented
@bogdandrutu it looks like the use of a constant that can be set at build time to control the choice of OTel or OpenCensus metrics will be easily converted to a feature gate when we have such a system.  I think this PR can be merged as-is.

2021-09-23 09:05 UTC, bogdandrutu approved these changes

2021-09-23 09:06 UTC, merged