Move ID from Config to CreateSettings for Exporter
open-telemetry/opentelemetry-collector pull request #3840
Opened 2021-08-17 00:27 UTC by bogdandrutu

Pros:
* The config.Exporter becomes now immutable;
* The obsreport needs only settings
* The exporter helper does not need config (will be removed in followup). Since config is opaque anyway.

Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

2021-08-17 05:10 UTC, tigrannajaryan requested changes
This has some implications which I am not completely certain about yet and which may prevent some interesting new functionality I was planning for config. I am on PTO until Auth 28, can we wait until then with this change, please?

2021-09-13 15:54 UTC, bogdandrutu commented
@tigrannajaryan I think we should discuss your concerns.

2021-11-24 19:25 UTC, codeboten reviewed
@tigrannajaryan @bogdandrutu what was the result of the followup discussion around this PR?

2021-11-29 18:45 UTC, tigrannajaryan commented
@bogdandrutu I don't remember if we discussed this. Do you? I think this looks fine, shouldn't cause problems that I was worried about.

2022-01-11 22:03 UTC, codeboten reviewed
@bogdandrutu are you planning on revisiting this PR or should it be closed?

2022-02-10 03:15 UTC, closed without merging