Reinstate website docs for auth
open-telemetry/opentelemetry-collector pull request #4041
Opened 2021-09-14 14:22 UTC by jpkrohling

This change reinstates the website docs for the auth capabilities, resolving https://github.com/open-telemetry/opentelemetry.io/issues/673 . 

Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

2021-09-14 14:23 UTC, jpkrohling commented
@austinlparker, would you be available for a review?

2021-09-14 14:32 UTC, bogdandrutu commented
@jpkrohling can you explain why these changes disappeared?

2021-09-14 15:56 UTC, jpkrohling commented
Apparently, I opened a PR against the website repository (https://github.com/open-telemetry/opentelemetry.io/pull/605) instead of opening one here. At some point, an automated pull request (https://github.com/open-telemetry/opentelemetry.io/pull/649) between this repository here and the website repo got rid of the collector doc files I added.

2021-09-14 15:58 UTC, jpkrohling commented
@austinlparker, how can I get a build of the website locally with the files from this PR? I wanted to validate whether the check-links failures are real.

2021-09-14 16:19 UTC, austinlparker commented
You'd need to sync the changes locally and run the build from the website repo.

2021-09-14 16:20 UTC, austinlparker approved these changes

2021-09-14 16:21 UTC, austinlparker commented
Would those check link tests ever pass? They're looking for things in the website repo. Glancing over them, they look fine, I'd just merge and I can edit the PR on the website side if needed.

2021-09-15 13:27 UTC, chalin commented
> Apparently, I opened a PR against the website repository ([open-telemetry/opentelemetry.io#605](https://github.com/open-telemetry/opentelemetry.io/pull/605)) instead of opening one here. At some point, an automated pull request ([open-telemetry/opentelemetry.io#649](https://github.com/open-telemetry/opentelemetry.io/pull/649)) between this repository here and the website repo got rid of the collector doc files I added.

Oh my, this is precisely the sort of issue that https://github.com/open-telemetry/opentelemetry.io/issues/730 is going to prevent. 

Note that we're in the process of **migrating the collector docs back into the website repo** ([opentelemetry.io#731]), so @jpkrohling et al., could we **stop submitting doc PRs here**?

Once [opentelemetry.io#731] is merged, than I'd be glad to reinstate https://github.com/open-telemetry/opentelemetry.io/pull/649 for you (@jpkrohling), if you'd like.

Apologies for the turmoil as we work our way through [opentelemetry.io#731].

[opentelemetry.io#731]: https://github.com/open-telemetry/opentelemetry.io/issues/731

2021-09-15 14:22 UTC, austinlparker commented
Can we make sure that https://github.com/open-telemetry/opentelemetry.io/issues/731 includes the content being re-added in this PR? That will make this one moot I believe.

2021-09-15 14:34 UTC, chalin commented
> Can we make sure that [open-telemetry/opentelemetry.io#731](https://github.com/open-telemetry/opentelemetry.io/issues/731) includes the content being re-added in this PR? That will make this one moot I believe.

That's the end result we want, but I'd rather handle the addition separately, and get #4042 merged into this repo ASAP.

2021-09-15 14:53 UTC, austinlparker requested changes
per @chalin, let's get https://github.com/open-telemetry/opentelemetry-collector/pull/4042 merged first then we can fix this in the right place.

2021-09-15 15:21 UTC, jpkrohling commented
Thanks for the heads-up! I'm closing this in favor of the the having the docs in the website's repo again.

2021-09-15 15:21 UTC, closed without merging