Include Query Params in request map for configauth
open-telemetry/opentelemetry-collector pull request #4793
Opened 2022-02-02 15:22 UTC by neelayu

**Description:** <Describe what has changed. 
Feature to include query params along with header in confighttp to pass to authenticator function.

**Link to tracking Issue:** NA

**Testing:** Unit

It would be good to have query params added to the "headers" map when considering http auth. The reason is for custom auth extensions could need data from query string(ex api_key, token) for authentication. This PR includes the query params in the headers itself which is renamed to a more generic `requestMap`. This allows non-breaking change for existing gRPC auth as well.

2022-02-02 18:25 UTC, bogdandrutu requested changes
Soon we will copy everything 10 times... I think we need to stop limiting. If you want have "headers" + "other stuff" instead of creating maps after maps.

@jpkrohling please provide a design doc of where you want to get with this.

2022-02-03 05:21 UTC, neelayu commented
Sure. The func signature defines headers which works for both gRPC and HTTP. However the actually request instances are different for both. So we can make use of this approach, or pass the value in the context, which I feel might obfuscate a lot of things.

2022-02-04 10:12 UTC, jpkrohling commented
I'm converting this to a draft, as it's clear that we want to have a better generic way to handle this. @neelayu, could you please create an issue to track this? I'll share my thoughts there once the issue is opened.

2022-02-04 10:20 UTC, neelayu commented
Created #4806

2022-03-05 09:23 UTC, bogdanov1609 commented
> I'm converting this to a draft, as it's clear that we want to have a better generic way to handle this. @neelayu, could you please create an issue to track this? I'll share my thoughts there once the issue is opened.

@neelayu @jpkrohling could you please provide relevant issue for this pr? We are interested in this feature and maybe can help.

2022-03-07 11:38 UTC, neelayu commented
> > I'm converting this to a draft, as it's clear that we want to have a better generic way to handle this. @neelayu, could you please create an issue to track this? I'll share my thoughts there once the issue is opened.
> 
> @neelayu @jpkrohling could you please provide relevant issue for this pr? We are interested in this feature and maybe can help.

@bogdanov1609 

#4806 is the issue where the discussions were taking place. Thanks!

2022-04-05 03:19 UTC, closed without merging