[exporter/logging] Add feature gate to build exporter from service's logger
open-telemetry/opentelemetry-collector pull request #5677
Opened 2022-07-12 15:29 UTC by mx-psi

**Description:**

Create `exporter.logging.CreateLoggerFromCore` feature gate, to build the exporter's logger from the service's logger.

Changing this is a breaking change, since right now setting e.g. `telemetry::logs::level: info` and `exporter::logging::loglevel: debug` will  make the logging exporter log at a debug level; while with the feature gate enabled, the exporter will fail to build (zap only allows increasing the level of a core in general, see https://github.com/uber-go/zap/issues/581#issuecomment-603557737 ).

**Link to tracking Issue:** Updates #5652

**Documentation:** Documented the feature gate.

2022-07-12 15:33 UTC, mx-psi commented
Some alternatives I considered:

- Log everything as 'info', and use the `loglevel` field to consider what to log.
- Ignore `loglevel` when lower than `telemetry::logs::level`

I think ultimately the right choice is to get rid of `loglevel` and just rely on `telemetry::logs::level` (but I will leave that for another PR :) )

2022-07-12 15:50 UTC, tigrannajaryan requested changes
Arguably, the current behavior (not this PR's behavior) is desirable. When I am troubleshooting I often add a `logging` exporter and set it to `debug` level. I don't also want to enable `debug` level for everything else, it will be just too much noise in the logs.

If we feel there is inconsistency because `logging` exporter's `debug` level does not honour the main level setting, I suggest we do something else instead: the "loglevel" setting of the `logging` exporter should control whether the detailed output is generated, _however_ that detailed output should be generated using `info` level, not `debug` level. So, essentially "loglevel" setting will control the behavior of the `logging` exporter, not the behavior of the `logging` exporter's logger. All output from `logging` exporter will happen at the `info` level. Once that change is made you can then pass the service's logger to the `logging` exporter to use.

2022-07-12 16:37 UTC, mx-psi commented
Right, this was the first alternative mentioned in https://github.com/open-telemetry/opentelemetry-collector/pull/5677#issuecomment-1181917506. It feels a bit weird to me, but I understand your point about wanting to filter the logs.

PTAL at #5678 which implements the suggested change. I will update this PR once that one is merged, marking as draft until then

2022-07-13 08:48 UTC, mx-psi commented on exporter/loggingexporter/factory.go
> +	CreateLoggerFromCoreFeatureGate = "exporter.logging.CreateLoggerFromCore"
There are now no breaking changes

2022-07-13 08:49 UTC, mx-psi commented
Rewritten to not have breaking changes; depends on #5678

2022-07-13 14:45 UTC, mx-psi commented
@tigrannajaryan this is ready for another look, I updated the PR description; this no longer introduces any breaking changes

2022-07-13 19:45 UTC, mx-psi commented on exporter/loggingexporter/factory.go
> +	core := zapcore.NewSamplerWithOptions(
This changes the encoding to whatever is set on `service::telemetry::logs::encoding`, but that's intended. Why would you want to have a different encoding for the logging exporter?  If I pass options to `CollectorSettings::LoggingOptions` or modify the `service::telemetry::logs` section, I expect this exporter to follow these settings, just like any other component would. I think the example on this configuration file is specially telling: https://github.com/open-telemetry/opentelemetry-collector/issues/5652#issue-1298642171; it's rather unusual to have an exporter report to `stderr` when the rest of the components are reporting to a file.

It's not possible to change the encoder while preserving other options on zap, so we have to choose between preserving the encoding (even when the user is setting the encoding to something else) or honoring the other options.

2022-07-14 16:22 UTC, tigrannajaryan approved these changes

2022-07-15 13:51 UTC, codeboten approved these changes

2022-07-15 14:13 UTC, merged