[chore] remove unused member from confmap.Resolver
open-telemetry/opentelemetry-collector pull request #6489
Opened 2022-11-07 22:37 UTC by bogdandrutu

This may be a breaking change, but should not be really important...

2022-11-07 23:02 UTC, Aneurysm9 requested changes
> This may be a breaking change, but should not be really important...

I don't think we get to make that decision for users of this framework.

2022-11-07 23:13 UTC, bogdandrutu commented
@Aneurysm9 who gets?

2022-11-07 23:15 UTC, bogdandrutu commented
Extracting @Aneurysm9 comment from the Slack channel

>  I think that means it should be included in the changelog so that users who are trying to figure out what broke when they update aren’t stumped by missing changes in the changelog

I think it is a fair comment, doing that now.

2022-11-08 19:37 UTC, codeboten approved these changes

2022-11-08 19:37 UTC, merged