add semantic conventions for specification v1.16.0
open-telemetry/opentelemetry-collector pull request #6713
Opened 2022-12-08 22:20 UTC by frzifus

**Description:** 
Add semantic conventions for specification [v1.16.0](https://github.com/open-telemetry/opentelemetry-specification/releases/tag/v1.16.0).

**Link to tracking Issue:** 
Belongs to https://github.com/open-telemetry/opentelemetry-collector/issues/6696#issuecomment-1343135506

**Additional:** 

Convention type `trace` trace leads to the following output:
```
panic: unable to render template: exit status 1
Traceback (most recent call last):
  File "/usr/local/bin/gen-semconv", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/opentelemetry/semconv/main.py", line 67, in main
    semconv = parse_semconv(args, parser)
  File "/usr/local/lib/python3.8/site-packages/opentelemetry/semconv/main.py", line 38, in parse_semconv
    semconv.finish()
  File "/usr/local/lib/python3.8/site-packages/opentelemetry/semconv/model/semantic_convention.py", line 317, in finish
    fixpoint_ref = self.resolve_ref(semconv)
  File "/usr/local/lib/python3.8/site-packages/opentelemetry/semconv/model/semantic_convention.py", line 458, in resolve_ref
    raise ValidationError.from_yaml_pos(
opentelemetry.semconv.model.exceptions.ValidationError: Semantic Convention trace-exception reference `exception.type` but it cannot be found! - @2:5
```
According to the [sem-conv changelog](https://github.com/open-telemetry/build-tools/blob/v0.14.0/semantic-conventions/CHANGELOG.md), there should have been no breaking change. The last one was in version [v0.12.0](https://github.com/open-telemetry/build-tools/blob/v0.14.0/semantic-conventions/CHANGELOG.md#v0120) and was resolved [here](https://github.com/open-telemetry/opentelemetry-collector/pull/6213/files#diff-e8e0fbe7ca5796b64b1c0293e112c6c2eb012bf174a4856ccc78bd04c3f9bf73R19-R26).

Can someone help/show me what to look for?

2022-12-20 08:48 UTC, frzifus commented
any updates here @open-telemetry/collector-approvers ? :smiley:

2022-12-21 01:54 UTC, dmitryax approved these changes

2022-12-21 09:00 UTC, mx-psi approved these changes

2022-12-23 13:54 UTC, frzifus commented
Is something else needed? :)

2022-12-28 17:04 UTC, Aneurysm9 requested changes
It looks like you had to change the invocation used to generate these constants, but have not updated the `gensemconv` make target.  That needs to be done as well.  If changes are required in the generator then they should be made first and the dependency updated.

```console
$ make gensemconv SPECPATH=../opentelemetry-specification SPECTAG=v1.16.0
Generating semantic convention constants from specification version v1.16.0 at ../opentelemetry-specification
semconvgen -o semconv/v1.16.0 -t semconv/template.j2 -s v1.16.0 -i ../opentelemetry-specification/semantic_conventions/resource -p conventionType=resource -f generated_resource.go
semconvgen -o semconv/v1.16.0 -t semconv/template.j2 -s v1.16.0 -i ../opentelemetry-specification/semantic_conventions/trace -p conventionType=trace -f generated_trace.go
panic: unable to render template: exit status 1
Traceback (most recent call last):
  File "/usr/local/bin/gen-semconv", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/opentelemetry/semconv/main.py", line 67, in main
    semconv = parse_semconv(args, parser)
  File "/usr/local/lib/python3.8/site-packages/opentelemetry/semconv/main.py", line 38, in parse_semconv
    semconv.finish()
  File "/usr/local/lib/python3.8/site-packages/opentelemetry/semconv/model/semantic_convention.py", line 317, in finish
    fixpoint_ref = self.resolve_ref(semconv)
  File "/usr/local/lib/python3.8/site-packages/opentelemetry/semconv/model/semantic_convention.py", line 458, in resolve_ref
    raise ValidationError.from_yaml_pos(
opentelemetry.semconv.model.exceptions.ValidationError: Semantic Convention trace-exception reference `exception.type` but it cannot be found! - @2:5


goroutine 1 [running]:
main.main()
        /Users/mirabant/go/pkg/mod/go.opentelemetry.io/build-tools/semconvgen@v0.3.0/generator.go:61 +0x44e
make: *** [gensemconv] Error 2
```

2023-01-05 15:20 UTC, frzifus commented
Thanks for the feedback @Aneurysm9. I have adjusted the `Makefile` rule. But to use the rule, this [semconvgen patch](https://github.com/open-telemetry/opentelemetry-go-build-tools/pull/217) is needed.

2023-01-05 19:14 UTC, Aneurysm9 commented on Makefile
> +	semconvgen -o semconv/${SPECTAG} -t semconv/template.j2 -s ${SPECTAG} -i ${SPECPATH}/semantic_conventions/. --only=span -p conventionType=trace -f generated_trace.go
```suggestion
	semconvgen -o semconv/${SPECTAG} -t semconv/template.j2 -s ${SPECTAG} -i ${SPECPATH}/semantic_conventions --only=resource -p conventionType=resource -f generated_resource.go
	semconvgen -o semconv/${SPECTAG} -t semconv/template.j2 -s ${SPECTAG} -i ${SPECPATH}/semantic_conventions --only=span -p conventionType=trace -f generated_trace.go
```

2023-01-06 16:07 UTC, Aneurysm9 commented
Once the generator change is landed this will need to update `internal/tools/go.mod` to ensure the use of the newer generator.  Otherwise, LGTM.

2023-01-06 20:14 UTC, frzifus commented
@Aneurysm9 I updated the internal semconvgen to the latest version.

2023-01-06 20:30 UTC, Aneurysm9 commented
> @Aneurysm9 I updated the internal semconvgen to the latest version.

I just made a `v0.4.0` release.  Can you update to that quickly?

2023-01-06 20:30 UTC, Aneurysm9 approved these changes

2023-01-06 21:29 UTC, frzifus commented
done :+1:

2023-01-06 22:01 UTC, dmitryax approved these changes

2023-01-06 22:16 UTC, Aneurysm9 approved these changes

2023-01-06 23:34 UTC, merged