Update @codeboten affiliation to reality
open-telemetry/opentelemetry-collector pull request #8816
Opened 2023-11-07 19:09 UTC by bogdandrutu

Fix the denial that @codeboten lives in.

2023-11-07 19:12 UTC, codeboten requested changes

2023-11-07 19:12 UTC, codeboten commented on README.md
> +   - [Alex Boten](https://github.com/codeboten), ServiceNow
```suggestion
   - [Alex Boten](https://github.com/codeboten), ServiceNow
```

2023-11-07 19:13 UTC, bogdandrutu commented
PTAL @codeboten

2023-11-07 22:26 UTC, yurishkuro commented on README.md
> +   - [Alex Boten](https://github.com/codeboten), ServiceNow
harsh...

2023-11-07 22:32 UTC, bogdandrutu commented on README.md
> +   - [Alex Boten](https://github.com/codeboten), ServiceNow
@tedsuo what do you think?

2023-11-08 04:09 UTC, codeboten approved these changes

2023-11-08 04:09 UTC, merged