[chore] simplify replacements with one mod edit call instead of many
open-telemetry/opentelemetry-collector pull request #9259
Opened 2024-01-10 17:15 UTC by atoulme

This speeds up replacements and make build logs easier to parse.

2024-01-10 18:04 UTC, codeboten approved these changes

2024-01-10 18:04 UTC, codeboten requested changes
Looks like something's not working as expected:

```
 Setting contrib at /tmp/opentelemetry-collector-contrib to use this core checkout
/bin/bash: -c: line 1: unexpected EOF while looking for matching `"'
/bin/bash: -c: line 2: syntax error: unexpected end of file
```

2024-01-10 19:35 UTC, atoulme commented
tabs and spaces I bet. Looking.

2024-01-11 17:55 UTC, codeboten approved these changes

2024-01-11 17:55 UTC, merged