[chore][extension/zpages] move handlers inside zpageextension
open-telemetry/opentelemetry-collector pull request #9333
Opened 2024-01-21 07:30 UTC by atoulme

**Description:**
Move zpageextension handlers that can execute with public host APIs and CreateSettings information inside the zpageextension code, reducing dependency on service package.

Given that this change doesn't affect any public API, I have declared it under a chore PR.

2024-01-22 20:51 UTC, bogdandrutu requested changes
I understand that this makes sense, but I want to make sure we are not exposing new public APIs. I would like to better understand why is better to have the public API that exposes the internal graph vs having this logic here.

2024-01-22 20:51 UTC, bogdandrutu commented on extension/zpagesextension/internal/zpages/package_test.go
> +package zpages
`zpages` -> `templates`?

2024-01-23 18:45 UTC, bogdandrutu commented
>Hang on, I didn't touch the graph API in this PR. I just moved the other zpages functions that could be fulfilled from the zpages extension without access to internals.

I don't understand the motivation to have the "Extension" part move. I would understand that we do move the Trace/Metrics part, but I don't understand the Extension, there is no "logic" for me on why the code should be there. So if you convince me why (not just because it can :) ) I would be happy to move forward with this.

2024-01-24 07:10 UTC, atoulme commented
> I don't understand the motivation to have the "Extension" part move.

With those moves, I move all logic into the extension. It feels cleaner to me, since it all depends on public APIs from the collector, and it allows a better separation of concerns.
This is going to help stabilize the service package a bit, reduces the burden of maintenance - I can probably add a test or two for this function as part of the zpages extension, bump up coverage.

2024-02-01 21:47 UTC, atoulme commented
I don't know if I should divide up this PR in more cases or go for a big change with #9334 to make my intentions more apparent. I'll close this PR and concentrate on #9334.

2024-02-01 21:47 UTC, closed without merging