updated README.md file in otlpreceiver
open-telemetry/opentelemetry-collector pull request #9756
Opened 2024-03-14 12:31 UTC by AkhigbeEromo

**Description:** <Describe what has changed.> Updated the README.md file in otlpreceiver - Corrected the serialization format to OTLP-JSON

**Link to tracking Issue:** (https://opentelemetry.io/docs/specs/otel/protocol/file-exporter/)

**Documentation:** <Describe the documentation added.> Changed the serialization format from Protobuf-JSON to OTLP-JSON

2024-03-25 17:31 UTC, AkhigbeEromo commented
Hello @jpkrohling, can i please get a review

2024-04-01 11:39 UTC, mx-psi requested changes

2024-04-01 11:39 UTC, mx-psi commented on receiver/otlpreceiver/README.md
> +and processed accordingly. Note the serialization format needs to be [OTLP JSON](https://opentelemetry.io/docs/specs/otel/protocol/file-exporter/).
I think this is the right link, isn't it?
```suggestion
and processed accordingly. Note the serialization format needs to be [OTLP JSON](https://opentelemetry.io/docs/specs/otlp/#json-protobuf-encoding).
```

2024-04-01 17:46 UTC, AkhigbeEromo commented
Thank you @mx-psi

2024-04-02 08:51 UTC, mx-psi approved these changes

2024-04-02 12:21 UTC, merged